### ISSUE TITLE
Crash when deconstructing under shipping overlay.

### ISSUE THREAD

**Issue by pheaver** [SolraBizna/onizd#1]
Steps to reproduce:
1. Activate shipping overlay (LSHIFT+F3)
2. Press 'x' or click on Deconstruct

I triggered this error twice on the same colony using the above steps, but cannot reproduce it anymore. I think there's another step needed to trigger the bug consistently.

```
UnityEngine.Object.IsNativeObjectAlive (UnityEngine.Object o) (at <a35d771e78bd4d75a6f3aedeaad4d1ed>:0)
UnityEngine.Object.CompareBaseObjects (UnityEngine.Object lhs, UnityEngine.Object rhs) (at <a35d771e78bd4d75a6f3aedeaad4d1ed>:0)
UnityEngine.Object.op_Equality (UnityEngine.Object x, UnityEngine.Object y) (at <a35d771e78bd4d75a6f3aedeaad4d1ed>:0)
ZTransport.Patches+BuildToolHoverTextCardPath.Postfix (BuildToolHoverTextCard __instance, HoverTextDrawer drawer) (at <aba4a440c5b94775bca18d9072304c96>:0)
(wrapper dynamic-method) HoverTextConfiguration.DrawInstructions_Patch1(object,HoverTextScreen,HoverTextDrawer)
DeconstructToolHoverTextCard.UpdateHoverElements (System.Collections.Generic.List`1[T] selected) (at <a8d8cafbcd164cda9f477d36796bfc75>:0)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <a8d8cafbcd164cda9f477d36796bfc75>:0)
InterfaceTool.LateUpdate () (at <a8d8cafbcd164cda9f477d36796bfc75>:0)
DragTool.LateUpdate () (at <a8d8cafbcd164cda9f477d36796bfc75>:0)
```

**Comment by pheaver** [comment]
I accidentally reproduced the bug again:
1. Activate shipping overlay (LSHIFT+F3)
2. Place conveyor bridge down over an existing conveyor line
3. Press 'x' to deconstruct -- game crashes immediately

Let me know if there's anything else I can do.

**Comment by SolraBizna** [comment]
This issue is with the mod itself, and this issue tracker is for the server. The mod's issue tracker is [here](https://github.com/BloodyRum/ZTransport/issues).

Nevertheless, thank you for the report and the steps to reproduce. I'd encountered this bug once or twice, but didn't figure out a way to reproduce it reliably. We should have a fix uploaded within a few hours.
